#
#
# WORKFLOW FOR SERVING THE PROCESS OF MANUAL PERSONAL DEPLOYMENT OF DATASET PACKAGE
#
#
name: "[DIFW_manual] Dataset Personal CD"
run-name: "[DIFW_manual] Dataset Personal CD - ${{ inputs.dataset-name }}:${{ inputs.dataset-version }} - ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      # Name of dataset
      dataset-name:
        description: 'Dataset name'
        required: true
        type: string
      # Core framework branch
      core-framework-branch:
        description: 'Core framework branch'
        required: false
        type: string
      # Name of source dataset branch
      dataset-source-branch:
        description: 'Dataset branch'
        required: true
        type: string
      # Clean deploy
      clean-deploy:
        description: 'Flag indicate whether remove all AWS resources related with this deployment before deploy or not'
        required: false
        type: boolean
        default: false
      # Orchestration custom repository
      orchestration-repository-branch:
        description: 'Orchestration repository branch'
        type: string
        required: false
      # environment where to deploy
      environment:
        description: 'Environment'
        required: true
        type: choice
        options: ["dev"]

jobs:
  prepare-env:
    environment: ${{ inputs.environment }}
    runs-on: [ "linux-x64-small" ]
    outputs:
      all-environments-list: ${{ vars.ALL_ENVIRONMENTS_LIST }}
      aws-region: ${{ vars.AWS_REGION}}
      airflow-host: ${{ vars.AIRFLOW_EKS_AIRFLOW_HOST }}

    steps:
      - name: Environment variables
        run: "echo Environment variables prepared"

  # ====================================================================================================================
  # This job parse core version of dataset
  # ====================================================================================================================
  ci-init:
    needs: prepare-env
    runs-on: [ "linux-x64-small" ]
    outputs:
      difw-core-version: ${{ steps.parse-core-version.outputs.difw-core-version }}
    steps:
        - name: Parse core version
          id: parse-core-version
          uses: merck-gen/mf-difw-automation/.github/actions/difw_components/parse-core-framework-version@main
          with:
            dataset-repository-name: ${{ vars.DATASET_REPOSITORY_NAME }}
            dataset-name: ${{ inputs.dataset-name }}
            dataset-source-branch: ${{ inputs.dataset-source-branch }}
            srv-github-token: ${{ secrets.SRV_GITHUB_TOKEN }}
  # ====================================================================================================================
  # This job will recall reusable workflow difw_cd_dataset_resolver.yaml from v1.0.0-automation tag
  # ====================================================================================================================
  difw_cd_manual:
    needs: [prepare-env, ci-init ]
    uses: merck-gen/mf-difw-automation/.github/workflows/difw_resolver_cd_personal_dataset.yaml@main
    with:
      environment: ${{ inputs.environment }}
      core-framework-branch: ${{ inputs.core-framework-branch }}
      dataset-name: ${{ inputs.dataset-name }}
      dataset-source-branch: ${{ inputs.dataset-source-branch }}
      dataset-repository-name: ${{ vars.DATASET_REPOSITORY_NAME }}
      clean-deploy: ${{ inputs.clean-deploy }}
      all-environments-list: ${{ needs.prepare-env.outputs.all-environments-list }}
      difw-core-version: ${{ needs.ci-init.outputs.difw-core-version }}
      aws-region:  ${{ needs.prepare-env.outputs.aws-region }}
      airflow-host: ${{ needs.prepare-env.outputs.airflow-host }}
      artifactory-url: ${{ vars.ARTIFACTORY_URL }}
      orchestration-repository-branch: ${{ inputs.orchestration-repository-branch }}
    secrets: inherit