dataset_name: reports_records
region: us-east-1

resource_prefix: "abi_{{dataset_name}}"

# Global retry setting - can be overriden at the jon level
retries: 0
retry_delay: 60

_template_aws_accounts_:
  name: aws_accounts

_template_databricks_template_:
  name: databricks_template

airflow_tags :
  - "mrl_gmabi"

#schedule: "0 4 * * *"   # Runs at 4:00 AM UTC every day

platform : databricks

glue_databases: {}

s3_paths :
  latest_path: latest
  c_path: "{{dataset_name}}/c/"

placeholders:
  latest_bucket: "abi-data-{{env}}"

airflow_event_handlers:
  on_task_failure:
    email_message:
      to: gmabi-{{env}}-job-noti@merck.com
      subject: "Failure in {dag.dag_id}.{task.task_id}"
      html_content: |
        Task <b>{task.task_id}</b> failed with error:<br><pre>{exception}</pre><br>
        <a href="{airflow_url}/log?execution_date={execution_date:%Y%m%dT%H%M%S.%f}&amp;task_id={task.task_id}&amp;dag_id={dag.dag_id}">Log</a>
  on_task_success:
    all_tables: true
    email_message:
      to: gmabi-{{env}}-job-noti@merck.com
      subject: "Success in {dag.dag_id}.{task.task_id}"
      html_content: |
       Task <b>{task.task_id}</b> completed successfully
        <a href="{airflow_url}/log?execution_date={execution_date:%Y%m%dT%H%M%S.%f}&amp;task_id={task.task_id}&amp;dag_id={dag.dag_id}">Log</a>
        
jobs:
  # One job for each region that will run in sequence
  - name: json_loader
    type: spark_databricks
    retries: 1
    steps:
      - name: json_loader
        configuration:
          input:
            # Camel cased loader code - pipeline/spark/loaders
            format: json_pull
            # parameters passed to loader
            # _dev_ _tst_, _prod_ ar predefined based on run environment
            src_secret:
              _dev_: 'arn:aws:secretsmanager:us-east-1'
              _tst_: 'arn:aws:secretsmanager:us-east-1:'
              _prd_: 'arn:aws:secretsmanager:us-east-1:0598011'
            src_id: 39
            src_system: "{{dataset_name}}"
            catalog_name: "abi_{{env}}"
            stage_s3_bucket: "abi-data-{{env}}"
            stage_path: "stage_data/reports_records/"
            auth_url: "https://external.reports.link/auth/v1/integration/refresh-token"
            data_url: "https://external.reports.link/workflow/v1/workflows"
            reports_url: "https://external.reports.link/workflow/v1/reports"
            report_id_1: "675a312f-" 
            report_id_2: "ca2fa665-407"
            report_id_3: "9d91d22b-2"
            last_run_date: "2020-01-01"
            #last_run_date : "select min(last_run_date) from {catalog_name}.gmadw_integration_schema.src_map_dtl where src_id=12 and objct_id in(2,3,4,5,6,7,8,9,10);"
            # seperate by ; if using more than one email
            email_list: gmabi-{{env}}-job-noti@merck.com

  - name: json_to_csv_loader
    type: spark_databricks
    dependency:
      - json_loader
    retries: 1
    steps:
      - name: json_to_csv_loader
        configuration:
          input:
            # Camel cased loader code - pipeline/spark/loaders
            format: veevalink_workflow_json_to_csv
            # parameters passed to loader
            # _dev_ _tst_, _prod_ are predefined based on run environment
            src_id: 39
            src_system: "{{dataset_name}}"
            catalog_name: "abi_{{env}}"
            stage_volume_path: "/Volumes/abi_{{env}}/g_stage/report_columns"
            stage_s3_bucket: "abi-data-{{env}}"
            stage_path: "stage_data/reports_records/"
            auth_url: "https://external.reports.link/auth/v1/integration/refresh-token"
            data_url: "https://external.reports.link/workflow/v1/workflows"
            reports_url: "https://external.reports.link/workflow/v1/reports"
            report_id_1: "675a312f-" 
            report_id_2: "ca2fa665-"
            report_id_3: "9d91d22b-"
            last_run_date: "2020-01-01"
            # seperate by ; if using more than one email
            email_list: abi-{{env}}-job-noti@gmail.com  
            
  - name: pub_loader
    type: spark_databricks
    dependency:
      - json_to_csv_loader
    retries: 1
    steps:
      - name: pub_loader
        configuration:
          input:
            # Camel cased loader code - pipeline/spark/loaders
            format: pub_loader
            # parameters passed to loader
            # _dev_ _tst_, _prod_ are predefined based on run environment
            src_id: 39
            src_system: "{{dataset_name}}"
            catalog_name: "bi_{{env}}"
            stage_volume_path: "/Volumes/abi_{{env}}/stage/report_columns"
            # seperate by ; if using more than one email
            email_list: abi-{{env}}-job-noti@gmail.com  

  - name: common_sys_loader
    type: spark_databricks
    # dependency:
      # - veevalink_workflow_pub_loader
    retries: 1
    steps:
      - name: common_sys_loader
        configuration:
          input:
            # Camel cased loader code - pipeline/spark/loaders
            format: common_pub_sys_refresh_loader
            # parameters passed to loader
            data_set: "{{dataset_name}}"
            src_system: "{{dataset_name}}"
            catalog_name: "abi_{{env}}"
            # seperate by ; if using more than one email
            email_list: abi-{{env}}-job-noti@gmail.com            

  - name: archive_loader
    type: spark_databricks
    dependency:
      - pub_loader
    steps:
     - name: archive_loader
       configuration:
         input:
           # Camel cased loader code - dataset_modules/pipeline/spark/loaders
           format: archive_loader
           # parameters passed to loader
           # _dev_ _tst_, _prod_ are predefined based on run environment
           src_id: 39
           src_system: "{{dataset_name}}"
           stage_s3_bucket: "abi-data-{{env}}"
           archive_s3_bucket: "abi-data-{{env}}"
           stage_path: "stage_data/reports_records/"
           archive_path: "history_data/reports_records/"
           # seperate by ; if using more than one email
           email_list: abi-{{env}}-job-noti@gmail.com.com    
      
tables:
  - name: "{{dataset_name}}"
